### ISSUE TITLE
Colors are inverted on ILI9341

### ISSUE THREAD

**Issue by rangeli** [lvgl/lv_port_esp32#119]
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Describe the issue**
I flashed the example to my [M5Stack Gray](https://docs.m5stack.com/#/en/core/gray) and the colors were inverted.

I tried using the "Invert display" feature, but found that it actually flipped the display instead.

I was able to fix this by sending an invert display command to the ILI9341, but I had to modify the code to do this.

I've created a PR with the change, but I'm not sure if this issue only affects some M5Stack models.

**Code to reproduce the issue**

**Expected Results**

**Actual Results**

**ESP32 Chip version**

**ESP-IDF version**

**Development kit used**

**Development machine OS**

**Compilation warnings/errors (if available)**

**If possible, copy the compilation log into a file and attach it here**

**Comment by C47D** [comment]
Hi,

I don't have that dev kit, can you take a pic of the inverted colors? IIRC I had the same problem but with other display.

Based on your other issue, we may add an option to the display menu config named "Invert display colors" or something similar, so the users can enable/disable at will. What do you think?

**Comment by rangeli** [comment]
I think having a menu item for this might make sense, at least for the M5Stack/ILI9341.  I've made a PR with the fix BTW, but I could turn it into a menuconfig option.  Here's some pics of the display before and after the fix:
![image](https://user-images.githubusercontent.com/1470630/81382423-60d50700-90dc-11ea-8575-94eff5c645d6.png)

![image](https://user-images.githubusercontent.com/1470630/81382541-8feb7880-90dc-11ea-85f5-95ccc03f2897.png)

**Comment by C47D** [comment]
Thanks for the photo and PR, the problem can be specific to the M5Stack, I'm using the Wrover kit for my tests and I didn't got the inverted colors.

By any chance are you configuring the display orientation to any of the inverted options?

**Comment by barbiani** [comment]
Try to change your lv_conf.h to `#define LV_COLOR_16_SWAP   1`

**Comment by rangeli** [comment]
> Try changing your lv_conf.h to `#define LV_COLOR_16_SWAP 1`

Unfortunately, that doesn't work.  That option swaps the the 2 bytes of RGB565 color.  The fix needs to be a full invert of the colors.

**Comment by rangeli** [comment]
I've added a menuconfig option for this:

![image](https://user-images.githubusercontent.com/1470630/81468266-74e83980-91ac-11ea-8d1e-d32a53829396.png)

@C47D Can you look at my PR?

**Comment by C47D** [comment]
@rangeli Is this closed with #121 ?
