### ISSUE TITLE
Is it possible to read the ID of the screen chip?

### ISSUE THREAD

**Issue by guo652917087** [lvgl/lv_port_esp32#127]
Hi，
   Is it possible to read the ID of the screen chip? No read function is defined.
    I use ST7789V2
    Why does ST7789V use SPI mode 2?
   
   I modified and modified st7789.c to increase the vertical screen display:

   {ST7789_MADCTL, {0x80|0x20}, 1}, // Set to 0x28 if your display is flipped

**Comment by C47D** [comment]
> Is it possible to read the ID of the screen chip? No read function is defined.

Right now the display river only uses the MOSI signal, what register do you need to read to get the ID?

> I modified and modified st7789.c to increase the vertical screen display:
{ST7789_MADCTL, {0x80|0x20}, 1}, // Set to 0x28 if your display is flipped

Thanks for the code snippet, I will add more display orientation options to the ST7789, I got the IPS 240x240 display.

I had been busy updating the code for LVGL v7 and ILI9341 and ILI9488 displays, will work on the ST7789 now that I know you are using it.

**Comment by guo652917087** [comment]
@C47D 
Right now the display river only uses the MOSI signal, what register do you need to read to get the ID?
Reply：Now the screen display function is written directly. Can you consider that the "littlevgl" display will have a flower screen (the display is disordered), if I regularly (for example, 3 minutes) compare the content written in and the content read out is the same? Just to be more stable. My idea is that if you read the ST7789V ID (non-zero value), if the reading fails, the chip works abnormally, you need to reset ST7789V and reinitialize.
Because there is no reading function, even if my screen is removed, the program can be executed down.
I don't remember to be honest, it worked for me and I leave it like that, it doesn't work for you?
Reply：It works. I use  ST7789V2   (240*320)

**Comment by guo652917087** [comment]
No feedback, then I close this issue.
