### ISSUE TITLE
Is 8 pins paralell  ili9341 shield board  supported?

### ISSUE THREAD

**Issue by ghosttk** [lvgl/lv_port_esp32#129]
This shield has 8 lcd pins , there is no config options in menuconfig, where to assign these pinouts?

![](https://www.arduino.cn/data/attachment/forum/201906/13/160055aip4cfi88v3zknv8.jpg)

**Comment by C47D** [comment]
Currently the repository doesn't support parallel interface, only SPI and I2C.
To support it we would need to edit the code in several places, I will do some research if someone already ported lvgl to that controller in parallel mode.
