### ISSUE TITLE
using PWM to control the brightness of the screen.

### ISSUE THREAD

**Issue by guo652917087** [lvgl/lv_port_esp32#131]
Hi，
   I have a suggestion: Do you think about adding the function of using PWM to control the brightness of the screen. I use the development board "ESP-WROVER-KIT" and use the reference example of "https://github.com/espressif/esp-idf/tree/master/examples/peripherals/ledc", which can be designed to display on the screen at night The brightness gradually dims.

**Comment by C47D** [comment]
Hi, 

Not adding it directly but you can disable the backlight pin on the menuconfig and control the pwm on the application side of the code.
