### ISSUE TITLE
Driver for ST7796S

### ISSUE THREAD

**Issue by LuoJuly** [lvgl/lv_port_esp32#132]
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Can you add st7796s driver ? Thank you sir**

**It seems to be able to use the ili9341 driver, but it flashes every few seconds**

**ESP32 Chip version：ESP32-WROVER-B+ST7796S 320*480 3.5inch LCD SCREEN**

**Comment by LuoJuly** [comment]
![177c5fdd-50bc-46c2-9443-8efc3ec5126a](https://user-images.githubusercontent.com/25450131/82527608-70872d80-9b69-11ea-9b56-c628dfd54d77.jpg)

**Comment by C47D** [comment]
Hi,

I will take a look at the datasheet of it, I don't have any display with that driver at hand.
What version of ESP-IDF are you using?
