### ISSUE TITLE
lv_theme_material_init not found if configured with NO_THEME

### ISSUE THREAD

**Issue by Cikkcakk** [lvgl/lv_port_esp32#147]
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

**Describe the issue**

**Code to reproduce the issue**

**Expected Results**

**Actual Results**

**ESP32 Chip version**

**ESP-IDF version**

**Development kit used**

**Development machine OS**

**Compilation warnings/errors (if available)**

**If possible, copy the compilation log into a file and attach it here**

**Comment by C47D** [comment]
Can you test this branch https://github.com/lvgl/lv_port_esp32/tree/kconfig_themes

I've added theme configuration options in the menuconfig interface, you'll need to select an theme init function.

**Comment by C47D** [comment]
Merged into master, update your clone to test it.

**Comment by Cikkcakk** [comment]
there are no problems anymore with the latest master
