### ISSUE TITLE
Use branches, tags or releases

### ISSUE THREAD

**Issue by seeul8er** [lvgl/lv_port_esp32#155]
I am using this project as a submodule for my application. Currently, there are no branches or tags that I can use to easily identify different releases of this repository. The only thing I can do is link against some commit ID.

Could you consider tagging releases now and then when they are considered stable/tested or when major changes happened. For example, tagging the last commit that works with LVGL V6.x or creating a new branch for legacy v6 support.
I just updated my submodule and all that LVGL V7 magic broke my entire build. It's getting harder to instruct my users on how to successfully compile the project.

**Comment by seeul8er** [comment]
> We were considering creating ESP32 components for lv_examples, lvgl and lvgl_esp32_drivers separately, so i.e. users don't include lv_examples when not using it on their projects. Do you think this can be useful on your project?

That would be great! I'd definitely use the drivers repo. The other(s) could be for reference on a sample project only.

Thank you

**Comment by C47D** [comment]
I've posted this idea in the forum, here: [[RFC] ESP32 port repo, improvement suggestions](https://forum.lvgl.io/t/rfc-esp32-port-repo-improvement-suggestions/2485), it would be great if you can comment over there how this change would help your use case.

**Comment by embeddedt** [comment]
The new [branch scheme](https://github.com/lvgl/lvgl/branches) that's been rolled out across the core LVGL projects would address this issue, as it creates a new branch for each major version. We backported the logic to 6.x so there is a `release/v6` branch as well (even though it will likely never get another commit).

We should probably apply this to the current ESP32 repo even if we plan to replace it long-term.

**Comment by C47D** [comment]
Hi @embeddedt,

Great, I was planning to apply the new branch scheme once we have the separated repo for the esp32 drivers (because they changed a lot), they should work for v6 and v7. Or if you have another suggestion please let us know.

Thanks for the reminder.
