### ISSUE TITLE
variable "may be used uninitialized in this function"

### ISSUE THREAD

**Issue by KammutierSpule** [lvgl/lv_port_esp32#169]
When selecting ILI9488

On function sh1107_set_px_cb
CONFIG_LVGL_DISPLAY_ORIENTATION_LANDSCAPE
or
CONFIG_LVGL_DISPLAY_ORIENTATION_PORTRAIT

is not defined, so 
uint16_t byte_index;
    uint8_t  bit_index;
are not initialized.

**Comment by C47D** [comment]
Hi @KammutierSpule, it shouldn't raise a warning because only the source file for the chosen display is included into the build. What commit of the repo are you working on?

Anyways, I will initialize those variables to 0 if necessary.

**Comment by KammutierSpule** [comment]
sorry, you're right.. it was some issues with updating to the latest repo version.

**Comment by C47D** [comment]
No problem, have fun and let us know if you have more issues :)
