### ISSUE TITLE
Update LVGL and lv_example submodules

### ISSUE THREAD

**Issue by C47D** [lvgl/lv_port_esp32#188]
Currently we use LVGL 7.0.x, it would be great to update to LVGL 7.3.x to have the latest and greatest features of the project.

**Comment by kisvegabor** [comment]
Let me know if you need assistance from my side!

**Comment by C47D** [comment]
Will do, I've been a bit busy with my day job but I will start the update later today.

**Comment by C47D** [comment]
@kisvegabor both `lvgl` and `lv_examples` are now on the latest commit of the `release/v7` branch.

Still need to update the config and Kconfig files.

**Comment by kisvegabor** [comment]
Awesome!

What do you think, let's create Kconfig manually and think about auto-generating later?

**Comment by C47D** [comment]
Yes, I was thinking that, I can re use the Kconfig files that we already have.

**Comment by C47D** [comment]
Configuration files are still needed to update.
