### ISSUE TITLE
Update component.mk file

### ISSUE THREAD

**Issue by C47D** [lvgl/lv_port_esp32#197]
Maybe we can check for the `ESP_PLATFORM` variable.

**Comment by kisvegabor** [comment]
It seems a simple [ifdef](https://www.gnu.org/software/make/manual/html_node/Conditional-Syntax.html) can work:
```c
ifdef $(foo)
frobozz = yes
endif
```

**Comment by C47D** [comment]
Seems like `ESP_PLATFORM` is not defined when using make to bring up the menuconfig or cleaning the project, I'm getting the following warning messages:
``
/home/user/lv_port_esp32/components/lvgl_esp32_drivers/lvgl_touch/component.mk:1: warning: undefined variable 'ESP_PLATFORM'
/home/user/lv_port_esp32/components/lvgl_esp32_drivers/lvgl_tft/component.mk:1: warning: undefined variable 'ESP_PLATFORM'
/home/user/lv_port_esp32/components/lvgl_esp32_drivers/component.mk:1: warning: undefined variable 'ESP_PLATFORM'
/home/user/lv_port_esp32/components/lvgl/component.mk:1: warning: undefined variable 'ESP_PLATFORM'
/home/user/lv_port_esp32/components/lv_examples/component.mk:1: warning: undefined variable 'ESP_PLATFORM'
```

**Comment by C47D** [comment]
Needs further investigation
