### ISSUE TITLE
Display compatibility problem (other resolution than 800x480).

### ISSUE THREAD

**Issue by neilim** [lvgl/lv_port_esp32#227]
**The problem:**
480x272 display doesn't work properly.
**Why?**
I have found a bug in this file: _components/lvgl_esp32_drivers/lvgl_tft/FT81x.c_ in this function: void _TFT_bitmap_display(void)._
In this line:
_EVE_cmd_setbitmap(SCREEN_BITMAP_ADDR, EVE_RGB565, **800**, **480**);_
The resolution parameters are fixed to 800x480. If the configured display resolution is 480x272, then the library is unusable.
**Possible solution:**
If I modify this line to: _EVE_cmd_setbitmap(SCREEN_BITMAP_ADDR, EVE_RGB565, **EVE_HSIZE**, **EVE_VSIZE**);_ the display works fine with 800x480 and 480x272 also.

**Comment by davidjade** [comment]
Whoops. Thanks for catching that. I will get it fixed ASAP.

**Comment by C47D** [comment]
Thanks @neilim for reporting the issue, thanks @davidjade for the quick fix.
