### ISSUE TITLE
Moving driver to it's own repo

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_port_esp32#236]
Hi,

I think the last step to finish the "LVGL as an ESP component" project is to move the drivers to a separate repo. 

Are there any blocking issues to do this?

**Comment by C47D** [comment]
I can try moving the `lvgl_esp32_drivers` directory into the other repo as is, and fix errors, if any.

**Comment by C47D** [comment]
See test branch, I think I didn't broke anything 😄

**Comment by kisvegabor** [comment]
Cool, thanks! :slightly_smiling_face: 

It seems to me it works the same way as lvgl, and lv_examples - a "normal" ESP32 component that can be used directly in the component folder. Is it correct?

**Comment by C47D** [comment]
Yes, it's similar to those components, the only difference is the location of the Kconfig files. Because of that we need to tell the esp-idf framework the location of those files.

Just let me do another test and I will let you know when to merge it, what do you think?

**Comment by kisvegabor** [comment]
> Just let me do another test and I will let you know when to merge it, what do you think?

Perfect! :heart:

**Comment by C47D** [comment]
Closed with bfbc1c5d5fc729f76e0d3163f920dc26b5464c59
