### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by C47D** [lvgl/lv_port_esp32#241]
@kisvegabor and @embeddedt , I'm thinking on updating the README with some points:

- Better pictures, the current ones doesn't look nice (they suck to be honest, I'm not good at taking pictures).
- Remove the [install-this-project-as-a-library-submodule-in-your-own-project](https://github.com/lvgl/lv_port_esp32/#install-this-project-as-a-library-submodule-in-your-own-project) section, now the users can add LVGL and lvgl_esp32_drivers as separated submodules, they no longer need to add this whole repo.
- Update Platformio instructions.
- Cleanup in general.

Any other updates you think would be cool?

**Comment by kisvegabor** [comment]
Sounds good. 

I think the info in the README could be added to the [docs](https://docs.lvgl.io/latest/en/html/get-started/espressif.html) too. So we can keep them in sync at least to some extent. 

What do you think?

**Comment by C47D** [comment]
For reference: To update the README I'm working in [this](https://github.com/lvgl/lv_port_esp32/tree/update_readme) branch.

> I think the info in the README could be added to the docs too. So we can keep them in sync at least to some extent.
What do you think?

That's great, I think.

**Comment by C47D** [comment]
Closed with #245 and #248
