### ISSUE TITLE
how to control lv_indev_t *mouse without touchpad to move and click?

### ISSUE THREAD

**Issue by acer1204** [lvgl/lv_port_esp32#246]
my ili9341 tft is not touch version.
i want to control mouse by two adc as intput x,y.

this is my mouse init code, it will show x icon as cursor .

`lv_indev_t *mouse = lv_indev_get_next(NULL);`
`cursor = lv_label_create(lv_scr_act(), NULL);`
`lv_label_set_recolor(cursor, true);`
`lv_label_set_text(cursor, "x");`
`lv_indev_set_cursor(mouse, cursor);`
the lcd show x cursor icon.

when i use this api, it looks just move the x cursor icon not move mouse last position?
`lv_obj_set_pos(cursor, adc1, adc2);`

and then call click api. the lvgl just crash and reboot.
`const lv_point_t points_array[] =  { {40, 40}};`
`lv_indev_set_button_points(mouse, points_array);`

does anyone know how to control mouse without touchpad?

**Comment by embeddedt** [comment]
LVGL should move the cursor itself if you supply the correct input data in the input device's `read_cb` function. Please note that you need to use an input device of type `LV_INDEV_TYPE_POINTER` for the cursor to function correctly.

----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
