### ISSUE TITLE
Cannot Find  Components config->LVGL Configuration

### ISSUE THREAD

**Issue by BH2SEB** [lvgl/lv_port_esp32#257]
After I clone this repo , I cannot find LVGL Configuration in menuconfig while LVGL TFT Display Configuration and LVGL TOUCH Configuration is on the list.

Then I add an component.mk like this to fix this problem

COMPONENT_SRCDIRS := . 
COMPONENT_ADD_INCLUDEDIRS := .

**Comment by C47D** [comment]
Hi @BH2SEB,

I guess you're using `make menuconfig` to launch the menuconfig menu? I will check your proposal and include it.

**Comment by C47D** [comment]
Hi,

> After I clone this repo , I cannot find LVGL Configuration in menuconfig while LVGL TFT Display Configuration and LVGL TOUCH Configuration is on the list.

This is kind of expected because the main LVGL repository doesn't includes an `component.mk` file, this file is used when using make to build the project.

@kisvegabor Do you think it's possible to add the `component.mk` file in LVGL to support make based commands? All the ESP32 support were assuming the users using idf commands instead.

**Comment by kisvegabor** [comment]
> @kisvegabor Do you think it's possible to add the component.mk file in LVGL to support make based commands? All the ESP32 support were assuming the users using idf commands instead.

Yes! We can add `if`s to turn on/off the ESP related section.

**Comment by C47D** [comment]
@BH2SEB Can you try with the current master? I've added the components.mk file into LVGL

**Comment by tlechman49** [comment]
I'm experiencing a similar problem I think. When I bring the repo into my project using platformio or as a submodule I'm getting a lot of errors in compilation with trouble finding lv_conf.h and when I use menuconfig it doesn't find any of the LVGL related components. Seems like it can't find the kconfig files. 
I'd prefer to use platformio lib_deps which look like this inside plaformio.ini:
```
lib_deps = 
	lvgl=https://github.com/lvgl/lvgl.git#85c75c2f34ddde5ad0301b770255f41c8ed4c72a
	lvgl_esp32_drivers=https://github.com/lvgl/lvgl_esp32_drivers.git#6b08c3fcce0e12b44a171ef88059b52efc0269ad
```
But I've also pulled in as a submodule to lib: lib/lvgl and lib/lvgl_esp32_drivers

**Comment by C47D** [comment]
Hi @tlechman49,
Before we added the Kconfig files into LVGL and separated the drivers into it's own repo, we suggested to use this repo as a submodule. Correct me if I'm wrong, are you now using both LVGL and lvgl_esp32_drivers as submodules and not having issues?

I don't really have experience with Platformio, let me investigate how they manage dependencies.

**Comment by tlechman49** [comment]
I was previously using this repo as a submodule. I'm now hoping to bring the repos for LVGL and lvgl_esp32_drivers in as lib_deps with pio but if that can't be done I can always bring them in as submodules similar to whats in this repo's readme. 

I know pio stores the lib_deps libraries in .pio/libdeps/$ENVIRONMENT_NAME/$LIB_DEP_NAME.

**Comment by tlechman49** [comment]
I guess I misread your statement.. 

I was previously not having issues but I would like to upgrade to the latest version of the repo and am now having issues. When I pulled in the two repos as described in the readme and also when I pulled them in with lib_deps on a separate attempt I received errors during compilation regarding lv_conf.h.

**Comment by C47D** [comment]
Hi,

Before this repo used the `lv_conf.h` file to configure LVGL, it is now configured by using the menuconfig tool, when using menuconfig it doesn't needs the `lv_conf.h` file. So, when using LVGL as submodule (and it includes the Kconfig file) you should be able to use menuconfig.

Maybe we should update the README to note this.

**Comment by BH2SEB** [comment]
> @BH2SEB Can you try with the current master? I've added the components.mk file into LVGL

Thank you, the make menuconfig tool  is running normally now.

**Comment by C47D** [comment]
@tlechman49 Can you open a new issue with your problems?
