### ISSUE TITLE
ESP32S2 can't change display DC pin to gpio45 in vscode by using SDK configureation editor

### ISSUE THREAD

**Issue by Pupil2013** [lvgl/lv_port_esp32#282]
I‘m using the esp32s2,lcd driver st7789 ,vscode 
when change the lcd driver dc pin to 45,it will automatically change back to 2.

**Code to reproduce the issue**
Using the SDK Configuration editor
**Actual Results**
when change the lcd driver dc pin to 45,it will automatically change back to 2.
**ESP32 Chip version**
ESP32S2
**ESP-IDF version**
v4.2
**Development kit used**
VSCODE  ESP-IDF tool
**Development machine OS**
windows 10

**Comment by tore-espressif** [comment]
ESP32S2 has 43 GPIOs, see [datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf)

**Comment by Pupil2013** [comment]
> ESP32S2 has 43 GPIOs, see [datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf)

Yes it has 43 gpios,but here the io for DC line should be it's gpio pin name and esp32-s2 has gpio pin45 and pin46

**Comment by tore-espressif** [comment]
I see, sry. Will be fixed soon.

**Comment by cggulick** [comment]
I think GPIO45 on the ESP32-S2 is input only. Really sucks. The ESP32-S3 allows for all GPIO pins to be input or output.
