### ISSUE TITLE
Enabling examples

### ISSUE THREAD

**Issue by icodk** [lvgl/lv_port_esp32#284]
I try to enable the lv_demo_printer example but gets the following error:

`\build/../main/main.c:204: undefined reference to `lv_demo_printer'`

I followed the instructions in the examples README.md file: 
```

1.Copy lv_examples/lv_ex_conf_templ.h next to lv_examples directory
2.Rename it to lv_ex_conf.h
3.Change the first #if 0 to #if 1 to enable the file's content
4.Enable or Disable modules
```
Also added:
`#include "lv_examples/src/lv_demo_printer/lv_demo_printer.h"`

and then I call the lv_demo_printer() instead of the (original ) lv_demo_widgets()

For some reason the  lv_demo_printer() is not compiled (and none of the other examples which are not included by default)

**Comment by C47D** [comment]
What development kit and display are you using?
