### ISSUE TITLE
esp32s3  编译提示 error: 'HSPI_HOST' undeclared

### ISSUE THREAD

**Issue by yanwuguangjun** [lvgl/lv_port_esp32#291]
esp32-s3  编译提示 error: 'HSPI_HOST' undeclared 
是还没对  支持么

**Comment by HongLiangGong1990** [comment]
I encountered the same error!

**Comment by mydnc** [comment]
I am having the same error.

**Comment by mydnc** [comment]
Check this out:
https://github.com/lvgl/lv_port_esp32/issues/233

**Comment by tvanfossen** [comment]
https://github.com/espressif/esp-box

Depending on the display driver you are using, the esp-box repo works great for the S3 with LVGL.
