### ISSUE TITLE
The link to the forum when you write a PR/issue is incorrect

### ISSUE THREAD

**Issue by MrSurly** [lvgl/lv_port_esp32#326]
From this [PR](https://github.com/lvgl/lv_port_esp32/issues/324):

> We use GitHub issues for development related discussions.
> Please use the [forum](https://forum.littlevgl.com/) to ask questions.

The link above is to https://forum.littlevgl.com/, should be https://forum.lvgl.io/

**Comment by kisvegabor** [comment]
Thanks for pointing it out. I've fixed it here: https://github.com/lvgl/lv_port_esp32/commit/6e3bedb573ae2dd0cf38978752f57ddd01ac841b
