### ISSUE TITLE
Set rotation of display on menuconfig

### ISSUE THREAD

**Issue by C47D** [lvgl/lv_port_esp32#88]
The rotation of the display should be available for all supported displays.

**Comment by C47D** [comment]
Supported in ILI9341 and ST7789 so far.

**Comment by BFFonseca** [comment]
Hello.
Is there any way to set the rotation to 180º or 270º? This would be a good feature on menuconfig.

My display is upside down
![photo_2020-05-04_12-13-44](https://user-images.githubusercontent.com/49754867/80960424-ba011a00-8e00-11ea-805c-b4a81aab507f.jpg)

Sorry if this isn't the right place to ask.

**Comment by C47D** [comment]
@BFFonseca Hi, is that an ILI9341 based display?

**Comment by BFFonseca** [comment]
> @BFFonseca Hi, is that an ILI9341 based display?

Yes! It is an ILI931 320x240 with an XPT2046.

I was able to rotate the screen by hardcoding on the ili_init_cmds[] structure's 0x36 command with a value of 0xE8, like so:
![rotation_fix_hardcoded](https://user-images.githubusercontent.com/49754867/80967957-18cd9000-8e0f-11ea-8906-924db6f49c9a.png)

**Comment by BFFonseca** [comment]
I am guessing this is not a very clean way to do it, but it was the only fix I could find.
I've started working on this lib only a couple days ago.
Would be nice if there was a way of getting the 4 possible rotations (0º, 90º, 180º and 270º) on the menuconfig.

**Comment by C47D** [comment]
Don't worry, I just turned on my PC, I will let you know when I add the options to the menuconfig.

**Comment by BFFonseca** [comment]
> Don't worry, I just turned on my PC, I will let you know when I add the options to the menuconfig.

Alright, looking forward to it.

By the way, I based myself on this library that I used in Arduino before: https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_Drivers/ILI9341_Rotation.h

**Comment by C47D** [comment]
Thanks for the link I will check it. I'm pushing my changes here: https://github.com/littlevgl/lv_port_esp32/tree/ili9341_rotation

Problem is the four orientations seems to work on the Wrover Kit v4.1 (it have an embedded display with the same ILI9341 controller), but only landscape mode works on the display with the separated ILI9341 controller (like yours).

**Comment by C47D** [comment]
@BFFonseca Hi, i think i found the root issue, commit d6f6e18 on the `ili9341_rotation` branch seems to fix all 4 rotations, can you test that branch and let me know if it works for you?

I've tested it locally but is better if you can test it as well.

**Comment by BFFonseca** [comment]
I can confirm it's fixed!
All 4 rotations and the touch work fine.
Touch coordinate are switched up, but that's to be expected.

Thank you! Excellent work.

Portrait:
![portrait](https://user-images.githubusercontent.com/49754867/81172795-d8008300-8f96-11ea-9e19-60a0ccabc1d0.jpg)

Portrait Inverted:
![portrait_inverted](https://user-images.githubusercontent.com/49754867/81172798-dd5dcd80-8f96-11ea-8018-35a005488f2c.jpg)

Landscape:
![landscape](https://user-images.githubusercontent.com/49754867/81172804-e058be00-8f96-11ea-8356-8a31cdf91633.jpg)

Landscape Inverted:
![landscape_inverted](https://user-images.githubusercontent.com/49754867/81172807-e189eb00-8f96-11ea-9183-8d69d86e768d.jpg)

Suggestion for future implementation: Auto-rotate the touch coordinated based on screen rotation.

**Comment by C47D** [comment]
Thanks for testing it @BFFonseca :) , I think you can swap X and Y coordinates on the touch menu. I didn't tested it.

Sure, we could try to make the coordinate swap automagically, based on the rotation, let's leave that for another time.

**Comment by BFFonseca** [comment]
@C47D no problem. Was a feature I needed, so thank you!

Yes, that is what I did, and it's not hard to do anyway. I would be a nice to have feature, but indeed not a priority.

Yes, you can use my pictures on the README :)

**Comment by C47D** [comment]
All displays with rotation support are currently available in the menuconfig.
